[versions]

kotlin = "2.1.0"
compose = "1.7.3"
agp = "8.7.3"
androidx-activityCompose = "1.10.0"
sdp_ssp_version = "1.0.4"
network_monitor_version = "1.0.1"

[libraries]

androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
sdp-ssp = { module = "network.chaintech:sdp-ssp-compose-multiplatform", version.ref = "sdp_ssp_version" }
network-monitor = { module = "network.chaintech:compose-connectivity-monitor", version.ref = "network_monitor_version" }

[plugins]

multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.29.0" }